name: app-gcp

on:
  push:
    branches: [main]
    paths:
    - app/gcp/**

  workflow_dispatch:

jobs:
  gcp-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Authenticate
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Docker Build
        shell: bash
        run: |
          echo "aws codeartifact get-authorization-token"
          ARTIFACTS_AUTH=$(aws codeartifact get-authorization-token \
          --domain wheelercloudguru \
          --query authorizationToken \
          --output text)

          echo "docker build app/gcp"
          docker build app/gcp \
          --build-arg ARTIFACTS_AUTH=${ARTIFACTS_AUTH} \
          --tag wheeler146/resume:gcp-latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME

      - name: Docker Push to Docker Hub
        run: docker push wheeler146/resume:gcp-latest

      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: wheeler-resume
          service_account_key: ${{ secrets.GCP_SECRET_KEY }}

      - name: Docker Push to Container Registry
        run: docker push gcr.io/wheeler-resume/resume:gcp-latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wheelercloudguru \
          --image gcr.io/wheeler-resume/resume:gcp-latest \
          --region us-central1
