name: app-gcp

on:
  push:
    branches: [main]
    paths:
    - app/gcp/**

  workflow_dispatch:

jobs:
  gcp-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: GCP Auth
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: wheeler-resume
          service_account_key: ${{ secrets.GCP_SECRET_KEY }}

      - name: Docker Auth
        run: gcloud auth configure-docker --quiet

      - name: Docker Build
        shell: bash
        run: |
          echo "aws codeartifact get-authorization-token"
          ARTIFACTS_AUTH=$(aws codeartifact get-authorization-token \
          --domain wheelercloudguru \
          --query authorizationToken \
          --output text)

          echo "docker build app/gcp"
          docker build app/gcp \
          --build-arg ARTIFACTS_AUTH=${ARTIFACTS_AUTH} \
          --tag gcr.io/wheeler-resume/app-gcp:${GITHUB_SHA}

      - name: Docker Push
        run: docker push gcr.io/wheeler-resume/app-gcp:${GITHUB_SHA}

      - name: Cloud Run Deployment
        run: |
          gcloud run deploy wheelercloudguru \
          --image gcr.io/wheeler-resume/app-gcp:${GITHUB_SHA} \
          --region us-central1
          
