name: app-azure

on:
  push:
    branches: [main]
    paths:
    - app/azure/**

  workflow_dispatch:

jobs:
  azure-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Maven Config
        uses: s4u/maven-settings-action@v2.4.1
        with:
          servers: '[{"id": "codeartifact", "username": "aws", "password": "${env.ARTIFACTS_AUTH}"}]'

      - name: Build Script
        shell: bash
        run: |
          cd app/azure
          chmod +x ./build.sh
          ./build.sh

      - name: Azure Functions Deployment
        uses: Azure/functions-action@v1
        id: wheelercloudguru
        with:
          app-name: wheelercloudguru
          package: app/azure/target/azure-functions/wheelercloudguru
          publish-profile: ${{ secrets.AZURE_APP_AUTH }}

