name: App Azure Deployment

on:
  push:
    branches: [main]
    paths:
    - app/azure/**
    - app/core/**

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Install Core
        run: |
          cd app/core
          mvn clean install

      - name: Package Azure
        run: |
          cd app/azure
          mvn clean package

      - name: Upload to Azure Functions
        uses: Azure/functions-action@v1
        id: wheelercloudguru
        with:
          app-name: wheelercloudguru
          package: app/azure/target/azure-functions/wheelercloudguru
          publish-profile: ${{ secrets.AZURE_APP_AUTH }}

