name: App Deployment (GCP)

on:
  push:
    branches: [main]
    paths:
    - app/gcp/**

  workflow_dispatch:

jobs:
  docker-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Authenticate
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Docker Build
        shell: bash
        run: |
          echo "aws codeartifact get-authorization-token"
          ARTIFACTS_AUTH=$(aws codeartifact get-authorization-token \
          --domain wheelercloudguru \
          --query authorizationToken \
          --output text)

          echo "docker build app/gcp"
          docker build app/gcp \
          --build-arg ARTIFACTS_AUTH=${ARTIFACTS_AUTH} \
          --tag wheeler146/resume:gcp-latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME

      - name: Docker Push
        run: docker push wheeler146/resume:gcp-latest
