name: App Gcp Deployment

on:
  push:
    branches: [main]
    paths:
    - app/core/**
    - app/gcp/**

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Install Core
        run: |
          cd app/core
          mvn clean install

      - name: Docker Build
        run: docker build app/gcp -t wheeler146/resume:gcp-latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME

      - name: Docker Push
        run: docker push wheeler146/resume:gcp-latest
