name: App Deployment

on:
  push:
    branches: [main]
    paths:
    - app/**

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Package
        run: |
          cd app
          mvn clean package

      - name: Upload to Azure Functions
        uses: Azure/functions-action@v1
        id: wheelercloudguru
        with:
          app-name: wheelercloudguru
          package: app/target/azure-functions/wheelercloudguru
          publish-profile: ${{ secrets.AZURE_APP_AUTH }}

