name: Web Deployment

on:
  push:
    branches: [main]
    paths:
    - web/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          cd web
          npm install
          npm install -g @angular/cli

      - name: Test Angular
        run: |
          cd web
          ng test --browsers ChromeHeadless --watch=false

      - name: Build Angular
        run: |
          cd web
          ng build --prod

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: web/dist/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEB_AUTH }}

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Upload to Azure Blob
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name wheelercloudguruweb -d '$web' -s dist/

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge \
              --content-paths  "/*" \
              --name "wheelercloudguru" \
              --profile-name "wheelercloudguru" \
              --resource-group "wheelercloudguru"

      - name: Azure Logout
        run: |
          az logout
